project:
  type: book
  output-dir: docs

book:
  title: "Matemáticas y Estadística Farmacia"
  author:
    - "Alirio Cruz"
    - "Irene García"
  date: last-modified
  reader-mode: true
  page-footer:
    left: |
      Matématicas y Estadística para Farmacia
    right: |
     Este libro se ha creado con  <a href="https://quarto.org/">Quarto</a>.
  cover-image: Figuras/atlas.jpeg
  favicon: Figuras/atlas.jpeg
  site-url: https://Cruzalirio.github.io/Farmacia
  repo-url: https://github.com/Cruzalirio/Farmacia
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - t1_MatesBasicas.qmd
    - t2_intro.qmd
    - referencias.qmd

bibliography: referencias.bib

format:
  html:
    theme: cosmo
    lang: es 
  # pdf:
  #   documentclass: scrreprt
  #   linkcolor: blue
  #   lang: es


