<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Los datos y sus tipos – Matemáticas y Estadística Farmacia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./referencias.html" rel="next">
<link href="./t2_intro.html" rel="prev">
<link href="./Figuras/atlas.jpeg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./t3_losDatosTipos.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Los datos y sus tipos</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Matemáticas y Estadística Farmacia</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Cruzalirio/Farmacia" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo lector">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./t1_MatesBasicas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Matemáticas básicas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./t2_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Representación gráfica y análisis de Datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./t3_losDatosTipos.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Los datos y sus tipos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#descripción-de-datos-cualitativos" id="toc-descripción-de-datos-cualitativos" class="nav-link active" data-scroll-target="#descripción-de-datos-cualitativos"><span class="header-section-number">3.0.1</span> Descripción de datos cualitativos</a></li>
  <li><a href="#tablas-de-frecuencias-multidimensionales" id="toc-tablas-de-frecuencias-multidimensionales" class="nav-link" data-scroll-target="#tablas-de-frecuencias-multidimensionales"><span class="header-section-number">3.0.2</span> Tablas de frecuencias multidimensionales</a></li>
  <li><a href="#diagramas-de-barras-bidimensionales" id="toc-diagramas-de-barras-bidimensionales" class="nav-link" data-scroll-target="#diagramas-de-barras-bidimensionales"><span class="header-section-number">3.0.3</span> Diagramas de barras bidimensionales</a></li>
  <li><a href="#ejercicio" id="toc-ejercicio" class="nav-link" data-scroll-target="#ejercicio"><span class="header-section-number">3.0.4</span> Ejercicio</a></li>
  <li><a href="#diagramas-de-mosaico" id="toc-diagramas-de-mosaico" class="nav-link" data-scroll-target="#diagramas-de-mosaico"><span class="header-section-number">3.0.5</span> Diagramas de mosaico</a></li>
  <li><a href="#descripción-de-datos-ordinales" id="toc-descripción-de-datos-ordinales" class="nav-link" data-scroll-target="#descripción-de-datos-ordinales"><span class="header-section-number">3.0.6</span> Descripción de datos ordinales</a></li>
  <li><a href="#descripción-de-datos-cuantitativos" id="toc-descripción-de-datos-cuantitativos" class="nav-link" data-scroll-target="#descripción-de-datos-cuantitativos"><span class="header-section-number">3.0.7</span> Descripción de datos cuantitativos</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Cruzalirio/Farmacia/edit/main/t3_losDatosTipos.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/Cruzalirio/Farmacia/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Los datos y sus tipos</span></h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<p>Las técnicas básicas de estadística descriptiva consisten en una serie de valores y gráficos que nos permiten resumir y explorar un conjunto de datos, con el objetivo final de entenderlos o describirlos lo mejor posible.</p>
<p>Los datos de los que disponemos suelen ser multidimensionales, en el sentido de que observamos varias características (<strong>variables</strong>) de una serie de individuos. Almacenamos estos datos en <strong>tablas de datos</strong> como la que presentamos abajo, donde cada columna corresponde a una variable y cada fila son los datos de un individuo concreto. Así, en esta tabla, cada fila representa un niño y cada columna recoge una de las características que hemos anotado: su nombre, su altura (en cm), su número de hermanos, el color de sus cabellos, el número semanal de refrescos que suele tomar, y su grado de satisfacción con un juego para móvil (entre 0 y 5).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-condensed caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Una pequeña tabla de datos sobre niños</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Nombre</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Altura</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Hermanos</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Cabello</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Refrescos semanales</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Satisfacción App</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Marta</td>
<td style="text-align: right;">135</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">rubio</td>
<td style="text-align: left;">2-3</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Laura</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">negro</td>
<td style="text-align: left;">2-3</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Xavier</td>
<td style="text-align: right;">138</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">negro</td>
<td style="text-align: left;">0-1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Joan</td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">castaño</td>
<td style="text-align: left;">4-5</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Maria</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">rojo</td>
<td style="text-align: left;">0-1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Maria</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">castaño</td>
<td style="text-align: left;">6 o más</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Precaución
</div>
</div>
<div class="callout-body-container callout-body">
<p>En este curso vamos a “sobrecargar” el término <strong>variable</strong>, en el sentido de que tendrá dos significados diferentes que esperamos que podáis distinguir según el contexto:</p>
<ul>
<li><p>Por un lado, llamaremos <strong>variable</strong> a una característica que puede tomar diferentes valores sobre diferentes individuos; cuando tenga este sentido, a veces le añadiremos el adjetivo <strong>poblacional</strong>. Por ejemplo, la altura de las personas (de todo el mundo, de un país, de una ciudad…) es una variable poblacional.</p></li>
<li><p>Por otro lado, también llamaremos una <strong>variable</strong> a un vector formado por los valores de una variable poblacional sobre los sujetos de una muestra. Por ejemplo, las alturas de los niños recogidas en la tabla forman una variable en este sentido.</p></li>
</ul>
</div>
</div>
<p>Los tipos básicos de datos que consideramos en este curso son los siguientes:</p>
<ul>
<li><p>Datos <strong>cualitativos</strong>. Son los que expresan una cualidad del individuo, como por ejemplo el sexo cromosómico (macho, hembra), el género de una persona (hombre, mujer, lesbiana, gay, bisexual, transexual, intersexual, asexual), tipos de cáncer (de mama, de colon, de próstata…)… Si solo pueden tomar dos valores (“Sí” o “No”, “Macho” o “Hembra”…) los llamamos <strong>binarios</strong> o <strong>dicotómicos</strong> y si pueden tomar más de dos valores, <strong>politómicos</strong> o <strong>multicotómicos</strong>, dependiendo de lo que queramos complicar los adjetivos. A los posibles valores que puede tomar un tipo de datos cualitativo se los suele llamar <strong>niveles</strong>.</p>
<p>Los datos cualitativos pueden ser iguales o distintos, y no admiten ningún otro tipo de comparación.</p></li>
<li><p>Datos <strong>ordinales</strong>. Son datos similares a los cualitativos, en el sentido de que expresan una cualidad del individuo, pero con la diferencia de que se pueden ordenar de manera natural. Por ejemplo, los niveles de gravedad de una enfermedad (sano, leve, grave, muy grave, …) o las calificaciones en un examen (suspenso, aprobado, notable, sobresaliente) son datos ordinales. En cambio, no se pueden ordenar de manera significativa los sexos o los tipos de cáncer de los individuos: por eso son datos cualitativos y no ordinales.</p>
<p>También se suele llamar a los posibles valores que puede tomar un tipo de datos ordinal sus <strong>niveles</strong>.</p></li>
<li><p>Datos <strong>cuantitativos</strong>. Son datos que se refieren a medidas que sean números genuinos, con los que tenga sentido operar, tales como edades, longitudes, pesos, tiempos, números de individuos, etc. Distinguimos dos tipos:</p>
<ul>
<li><p><strong>Discretos</strong>: Pueden tomar solo valores que avanzan a saltos y que podemos identificar con números naturales: número de hermanos, número de ingresos en un día en un hospital…</p></li>
<li><p><strong>Continuos</strong>: Podrían tomar cualquier valor real dentro de un intervalo si se pudieran medir con precisión infinita: altura, temperatura, tiempo…</p></li>
</ul></li>
</ul>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; padding: 10px; margin: 10px 0;">
<p><strong>Ejemplo:</strong></p>
<p>En la tabla anterior:</p>
<ul>
<li>La variable “Nombre” es cualitativa.</li>
<li>La variable “Altura” es cuantitativa continua.</li>
<li>La variable “Hermanos” es cuantitativa discreta.</li>
<li>La variable “Cabello” es cualitativa.</li>
<li>La variable “Refrescos semanales” es ordinal.</li>
<li>La variable “Satisfacción App” también es ordinal.</li>
</ul>
</div>
<p>Dos puntos relevantes a tener en cuenta y que justifican algunas clasificaciones que puede que encontréis dudosas en el ejemplo anterior:</p>
<ul>
<li><p><strong>No todo número es un dato cuantitativo.</strong> Solo los consideramos cuantitativos cuando son números genuinos, “de verdad”. Por ejemplo, si pedimos a un paciente que califique su dolor con un número natural de 0 a 10, no es un dato cuantitativo, sino ordinal:</p></li>
<li><p>No es una medida precisa del dolor; no son números “de verdad”, sino abreviaturas de “Nada”, “Un poquito”,…, “Matadme”.</p></li>
<li><p>Tener dolor 6 no significa “tener el doble de dolor” que tener dolor 3 (si lo significara, ¿cuál sería el valor correspondiente “al doble de dolor” que 7?). En cambio, una persona con 6 hermanos sí que tiene el doble de hermanos que si tuviera 3.</p></li>
<li><p>No tiene sentido sumarlos u operarlos en general. Por ejemplo, si yo tengo dolor de nivel 6 y tú tienes dolor de nivel 5, entre los dos no tenemos dolor de nivel 11. En cambio, si yo tengo 6 hermanos y tú 5, entre los dos sí que tenemos 11 hermanos.</p></li>
</ul>
<p>Este es justamente el caso de la variable “Satisfacción App” de la tabla anterior. Pese a que sus valores son números, el único contenido real que tienen es su orden: a la María que toma muchos refrescos le ha gustado la app bastante más que a la María que apenas toma refrescos.</p>
<ul>
<li><strong>La distinción discreto-continuo es puramente teórica</strong>. En realidad, todo dato es discreto porque no podemos medir nada con precisión infinita, pero las herramientas matemáticas “continuas” (derivadas, integrales, etc.) son mucho más potentes que las discretas, por lo que siempre que tenga sentido, es conveniente considerar una variable como continua.</li>
</ul>
<p>Observad, por ejemplo, la diferencia entre la altura, pongamos que medida en cm y redondeada a unidades como en la tabla anterior, y el número de hermanos. Ambos se presentan como números naturales, pero los números de hermanos no admiten mayor precisión, mientras que las alturas las podríamos medir, con los aparatos adecuados, en mm, en µm, en nm…. Como además las herramientas para tratar datos continuos son mucho más potentes, vamos a considerar las alturas como datos continuos, mientras que los números de hermanos no hay más remedio que tratarlos como discretos.</p>
<p>En concreto, <strong>es conveniente considerar en la práctica como datos continuos aquellos que dan lugar a números naturales muy grandes</strong>, como por ejemplo los números de glóbulos rojos en un litro de sangre, de bases nucléicas en un genoma, o de personas de un país. La diferencia entre diez millones, diez millones uno, diez millones dos… puede considerarse como continua: de hecho, si tomamos el millón como unidad, la diferencia está en la séptima cifra decimal.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hemos dicho que la variable “Cabello” es cualitativa. En principio, el color de los cabellos no tiene ningún orden “natural”. Pero si en un estudio definimos un orden claro para esta variable (por ejemplo, por la longitud de onda correspondiente) y este orden es relevante en nuestro estudio, habrá que considerarla una variable ordinal.</p>
<p>La variable “Refrescos semanales” es de un tipo de datos ordinales muy concreto que a veces se califican de <strong>cuantitativos agrupados</strong>: sus niveles se obtienen agrupando en intervalos los posibles valores de una variable cuantitativa (en este caso, la variable discreta que mide el número preciso de refrescos semanales).</p>
</div>
</div>
<blockquote class="blockquote">
<p>El análisis, tanto descriptivo como inferencial, de un conjunto de datos es diferente según su tipo.</p>
</blockquote>
<p>Así, para datos cualitativos sólo tiene interés estudiar y representar las frecuencias con que aparecen sus diferentes valores, mientras que el análisis de datos cuantitativos suele involucrar el cálculo de medidas estadísticas, como la media o la desviación típica, que expresen numéricamente sus propiedades.</p>
<section id="descripción-de-datos-cualitativos" class="level3" data-number="3.0.1">
<h3 data-number="3.0.1" class="anchored" data-anchor-id="descripción-de-datos-cualitativos"><span class="header-section-number">3.0.1</span> Descripción de datos cualitativos</h3>
<p>Los <strong>datos cualitativos</strong> corresponden a observaciones sobre cualidades de un objeto o individuo, tales como su especie o su sexo, que pueden ser iguales o diferentes y no admiten ningún otro tipo de comparación significativa: por ejemplo, datos para los que no tenga ningún sentido preguntarse si uno es más grande que otro, ni efectuar operaciones aritméticas con ellos, aunque estén representados por números. Llamaremos <strong>niveles</strong> a los diferentes valores que puede tomar una variable cualitativa; por ejemplo, los dos niveles de una variable “Sexo” serían “Macho” y “Hembra”, o sinónimos.</p>
<p>Lo único que podemos hacer con un conjunto de datos cualitativos es contar cuántas veces aparece cada nivel y presentar estas <strong>frecuencias</strong> en una tabla o por medio de un gráfico. Distinguiremos entre:</p>
<ul>
<li><p><strong>Frecuencia absoluta</strong> de un nivel: el número de veces que aparece en la muestra.</p></li>
<li><p><strong>Frecuencia relativa</strong> de un nivel: la fracción del total de la muestra que representa este nivel.</p></li>
</ul>
<p>Además, llamaremos la <strong>moda</strong> al nivel (o a los niveles, en caso de empate) más frecuente. A veces usaremos adjetivos como <strong>unimodal</strong>, <strong>bimodal</strong>, <strong>multimodal</strong> etc. para referirnos, respectivamente, a una variable con una sola moda, con dos modas, con “varias” modas, etc.</p>
<strong>Ejemplo:</strong>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; 
padding: 10px; margin: 10px 0;">
<p>Hemos recogido información sobre 20 residentes en geriátricos que en el período marzo-mayo de 2020 tuvieron COVID-19. Uno de los datos que hemos recogido sobre estas personas ha sido su sexo. El resultado ha sido una variable cualitativa, que llamaremos “Sexo”, formada por las 20 observaciones siguientes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Mujer,  Mujer,  Hombre,  Mujer,  Mujer,  Mujer,  Mujer,  Mujer,  Hombre, Mujer,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Hombre,  Hombre,  Mujer,  Mujer,  Hombre,  Mujer,  Mujer,  Mujer,  Mujer,  Hombre</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sus dos niveles son <em>Hombre</em> y <em>Mujer</em>. En esta variable hay 14 mujeres y 6 hombres. Por lo tanto, éstas son las frecuencias absolutas de estos niveles. Puesto que en total hay 20 individuos, sus frecuencias relativas son:</p>
<ul>
<li><p><em>Hombre</em>: 6/20=0.3</p></li>
<li><p><em>Mujer</em>: 14/20=0.7</p></li>
</ul>
<p>La moda de la muestra es el nivel Mujer.</p>
<p>Resumimos estas frecuencias en la <strong>tabla de frecuencias</strong> siguiente:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Frecuencia absoluta</th>
<th style="text-align: right;">Frecuencia relativa</th>
<th style="text-align: left;">Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hombre</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: left;">30%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mujer</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: left;">70%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: left;">100%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" type="rmdnote">

<div class="rmdnote">
<p>El término <strong>moda</strong> y los adjetivos <strong>unimodal</strong>, <strong>bimodal</strong>, etc. también se usan en variables poblacionales: dada una variable poblacional cualitativa, su <strong>moda</strong> es el nivel más frecuente en el total de la población, cuando existe.</p>
<p>Pero en el caso poblacional, decimos que la variable es <strong>unimodal</strong> cuando hay un nivel que es <em>mucho más frecuente</em> que el resto, no basta con que haya uno más frecuente. De manera similar, <strong>bimodal</strong> no significa que la mayor frecuencia de un nivel en la población se dé en dos niveles que empaten exactamente, sino que hay dos niveles con frecuencias parecidas y mucho mayores que el resto.</p>
<p>Por ejemplo, supongamos que tenemos una variable poblacional que puede tomar 4 valores excluyentes: A, B, C, D.</p>
<ul>
<li><p>Si en el total de la población los niveles A y B se dan, cada uno, en un 25.1% de los individuos, y los niveles C y D cada uno en un 24.9% de los individuos, no diremos que la variable sea bimodal.</p></li>
<li><p>Si en el total de la población el nivel A se da en un 42% de los individuos, el nivel B en un 41% de los individuos, el nivel C en un 9% y el nivel D en un 8%, sí que diremos que es bimodal, aunque A sea más frecuente que el resto.</p></li>
</ul>
</div>
</div>
</div>
<p>Con Jamovi, tras entrar los datos en una variable (importando un fichero de datos o entrándolos a mano en <strong>Datos</strong>), podéis calcular las tablas de frecuencias absolutas y relativas y el diagrama de barras de frecuencias absolutas de una variable cualitativa usando las casillas adecuadas de la sección <strong>Exploración/Descriptivas</strong>, tal y como se muestra en la imagen siguiente:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>Antes de continuar, observad que Jamovi incluye en la tabla de frecuencias una columna “% Acumulado” sin que se la pidamos. Solo la tendremos en cuenta si la variable es ordinal.</p>
<p>Un tipo muy popular de representación gráfica de variables cualitativas son los <strong>diagramas circulares</strong>, donde se representan los niveles de una variable cualitativa como porciones circulares de un círculo, de manera que el ángulo de cada porción (o equivalentemente, su área) sea proporcional a la frecuencia del nivel al que corresponde. Así, el diagrama circular de la variable dicotómica “Sexo” sería el siguiente:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:30.0%"></p>
</figure>
</div>
<p>Pese a su popularidad, es poco recomendable usar diagramas circulares cuando se manejan más de dos niveles, porque a veces es difícil, a simple vista, comprender las relaciones entre las frecuencias que representan. Para convencerse, basta comparar los diagramas de barras y los diagramas circulares de la figura siguiente, importada de la <a href="http://en.wikipedia.org/wiki/Pie_chart">entrada sobre diagramas circulares de la <em>Wikipedia</em></a>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Y por este motivo, por favor, <strong>nunca</strong> uséis diagramas circulares para más de dos niveles.</p>
</div>
</div>
<p>Un gráfico ha de servir más que mil palabras, y tiene que explicar de un vistazo las características más relevantes de los datos que representa. Luego ya se pueden añadir detalles que complementen esta primera comprensión básica. En el caso de un diagrama de barras, su objetivo ha de ser mostrar la relación entre las magnitudes de las frecuencias que representa; si nos interesan sus valores concretos, es mejor dar la tabla. Por ejemplo, en los diagramas de barras de la variable “Sexo” dados más arriba se ve a simple vista que hay aproximadamente el doble de mujeres que de hombres.</p>
<p>Por ese motivo es un pecado mortal modificar un gráfico para que el primer vistazo sea engañoso. En un diagrama de barras, la adulteración más usual, y ante la que hay que estar atentos, es <strong>truncarlo</strong> de manera que el eje de coordenadas que indique las frecuencias no arranque en el 0. Mirad, por ejemplo, el diagrama de barras siguiente:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
<p>Este diagrama sigue indicando que en la muestra hay un 30% de hombres y un 70% de mujeres, pero si le dais un vistazo superficial, sin mirar las marcas del eje vertical, parece que la proporción de mujeres es cinco veces la de los hombres y no un poco más del doble.</p>
<p>Es muy frecuente encontrar diagramas de barras (u otros tipos de gráficos) truncados en medios de comunicación. Por ejemplo mirad el gráfico siguiente,</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</section>
<section id="tablas-de-frecuencias-multidimensionales" class="level3" data-number="3.0.2">
<h3 data-number="3.0.2" class="anchored" data-anchor-id="tablas-de-frecuencias-multidimensionales"><span class="header-section-number">3.0.2</span> Tablas de frecuencias multidimensionales</h3>
<p>Cuando medimos más de una variable cualitativa sobre un mismo grupo de individuos, representamos sus frecuencias absolutas o relativas mediante <strong>tablas de contingencia</strong> multidimensionales.</p>
<strong>Ejemplo:</strong>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; 
padding: 10px; margin: 10px 0;">
<p>Continuemos con nuestra muestra de 20 pacientes en residencias geriátricas. Además de su sexo, hemos anotado otras dos características: una variable “Demencia” que recoge si en el momento del ingreso en la residencia habían sido diagnosticados con algún tipo de demencia senil, con niveles “No”, “Alzheimer” y “Otros” (para indicar otros diagnósticos de demencia no-Alzheimer), y una variable “Cancer” que indica si en algún momento han sufrido o no cáncer de mama.</p>
<p>La tabla de datos es la siguiente:</p>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-condensed caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla de datos de pacientes de residencias geriátricas</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">Sexo</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">Demencia</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">Cancer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">Sí</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">Sí</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">Sí</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Sí</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>La tabla bidimensional de frecuencias absolutas de las variables “Sexo” y “Demencia”, que nos da la frecuencia absoluta de cada combinación de sexo y tipo de demencia senil, es:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Alzheimer</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Otros</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hombre</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mujer</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>y la tabla tridimensional de frecuencias absolutas de las tres variables, que nos da la frecuencia absoluta de cada combinación de sexo, tipo de demencia senil y si se ha sufrido o no cáncer de mama, es:</p>
<p>Con Jamovi, estas tablas se obtienen fácilmente separando una variable por la otra (u otras) y marcando las mismas casillas en <strong>Exploración/Descriptivas</strong> que en el caso unidimensional:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-6.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-7.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<p>Las tablas bidimensionales se pueden obtener de manera más adecuada en <strong>Frecuencias/Muestras independientes</strong>: lo explicaremos dentro de un rato.</p>
<p>A menudo es conveniente añadir a una tabla de contingencia multidimensional, filas y columnas <strong>marginales</strong> (en los márgenes) con las frecuencias totales de cada nivel dentro de cada variable. De esta manera, también tenemos las tablas de frecuencias de cada una de las variables. Por ejemplo, si añadimos la fila y la columna marginales a la tabla bidimensional anterior obtenemos:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 6%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;">Alzheimer</th>
<th style="text-align: center;">Otros</th>
<th style="text-align: center;">No</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Hombre</strong></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Mujer</strong></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">20</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Las tablas multidimensionales de frecuencias relativas son algo más complicadas porque dichas frecuencias relativas se pueden calcular en el total de la muestra (las llamamos frecuencias relativas <strong>globales</strong>) o dentro de los niveles de una de las variables (por filas o por columnas, en el caso bidimensional), en función de lo que nos interese medir. Por ejemplo:</p>
<ul>
<li>Si nos interesa la fracción de pacientes de cada combinación de sexo y tipo de demencia senil en el total de la muestra, usaremos la tabla de frecuencias relativas globales de las variables “Sexo” y “Demencia”:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Alzheimer</th>
<th style="text-align: right;">Otros</th>
<th style="text-align: right;">No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hombre</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mujer</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.35</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Observad que la suma de todas las entradas de la tabla es 1, lo que indica que estas frecuencias indican proporciones del total de la muestra.</p>
<p>Por ejemplo, la entrada superior izquierda de esta tabla nos dice que los hombres con Alzheimer representan el 20% del total de la muestra. Es decir, si en nuestra muestra <span class="math inline">\(A\)</span> representa el suceso “Tener Alzheimer” y <span class="math inline">\(H\)</span> el suceso “Ser hombre”, esta entrada dice que <span class="math inline">\(P(A\cap H)=0.2\)</span>.</p>
<ul>
<li>Si nos interesa la fracción de pacientes con cada tipo de demencia senil dentro de cada sexo, usaremos la tabla de frecuencias relativas de la variable “Demencia” dentro de la variable “Sexo”:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Alzheimer</th>
<th style="text-align: right;">Otros</th>
<th style="text-align: right;">No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hombre</td>
<td style="text-align: right;">0.6667</td>
<td style="text-align: right;">0.1667</td>
<td style="text-align: right;">0.1667</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mujer</td>
<td style="text-align: right;">0.2857</td>
<td style="text-align: right;">0.2143</td>
<td style="text-align: right;">0.5000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En esta tabla, la suma de las entradas de cada fila es 1, lo que indica que las frecuencias son proporciones dentro de cada fila.</p>
<p>Por ejemplo, la entrada superior izquierda de esta tabla nos dice que los hombres con Alzheimer representan el 66.67% de los hombres de la muestra. Es decir, con las notaciones anteriores, que <span class="math inline">\(P(A|H)=0.6667\)</span>.</p>
<ul>
<li>Si nos interesa la fracción de pacientes de cada sexo dentro del grupo de pacientes con cada tipo de demencia senil, usaremos la tabla de frecuencias relativas de la variable “Sexo” dentro de la variable “Demencia”:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Alzheimer</th>
<th style="text-align: right;">Otros</th>
<th style="text-align: right;">No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hombre</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.125</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mujer</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.875</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En esta tabla, la suma de las entradas de cada columna es 1, lo que indica que las frecuencias son proporciones dentro de cada columna.</p>
<p>Por ejemplo, la entrada superior izquierda de esta tabla nos dice que los hombres con Alzheimer representan el 50% de los enfermos de Alzheimer de la muestra. O sea, de nuevo con las notaciones anteriores, que <span class="math inline">\(P(H|A)=0.5\)</span>.</p>
<p>En una tabla de contingencia de frecuencias relativas globales, tiene sentido añadir filas y columnas marginales, que nos darán las frecuencias relativas de los niveles de cada variable.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;">Alzheimer</th>
<th style="text-align: center;">Otros</th>
<th style="text-align: center;">No</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Hombre</strong></td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.3</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Mujer</strong></td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.7</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Pero en una tabla de contingencia de frecuencias relativas de una variable respecto de otra no tiene mucho interés. Por ejemplo, añadamos las marginales a la tabla de frecuencias relativas de la variable “Demencia” dentro de la variable “Sexo”:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">&nbsp;</th>
<th style="text-align: center;">Alzheimer</th>
<th style="text-align: center;">Otros</th>
<th style="text-align: center;">No</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Hombre</strong></td>
<td style="text-align: center;">0.6667</td>
<td style="text-align: center;">0.1667</td>
<td style="text-align: center;">0.1667</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Mujer</strong></td>
<td style="text-align: center;">0.2857</td>
<td style="text-align: center;">0.2143</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;">0.9524</td>
<td style="text-align: center;">0.381</td>
<td style="text-align: center;">0.6667</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como hemos calculado las frecuencias relativas dentro de cada fila, la suma de las frecuencias relativas de cada fila ha de ser 1. Ahora fijaos en la fila <strong>Total</strong>. Nos dice por ejemplo que la suma de la proporción de hombres que tienen Alzheimer, 0.6667, y de la proporción de mujeres que tienen Alzheimer, 0.2857, es 0.9523. ¿Qué significado tiene este número? Ninguno, y en todo caso <strong>de ninguna manera significa</strong> que la proporción de individuos con Alzheimer en la muestra sea 0.9523, ya que esta proporción es del 40%.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>A la hora de decidir qué variable asignamos a las filas y cuál a las columnas en una tabla de contingencia bidimensional, es conveniente recordar que, en los paises occidentales, solemos leer las tablas por filas y de izquierda a derecha. Por ello, si tenemos interés en la distribución de los niveles de una variable dentro de los niveles de una segunda variable, puede facilitar la lectura de la tabla que esta segunda variable defina las filas.</p>
</div>
</div>
<p>Las tablas de contingencia bidimensionales con frecuencias relativas marginales se obtienen con Jamovi en la sección <strong>Frecuencias/Muestras independientes</strong>. Por ejemplo, si declaramos la variable “Sexo” como la de las filas y la variable “Demencia” como la de las columnas y marcamos <em>Frecuencias observadas</em> en la pestaña <em>Celdas</em>, entonces podemos pedir en las casillas de la columna <em>Porcentajes</em> que se calculen las frecuencias relativas por filas, por columnas o en el total. Por ejemplo, por filas:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-8.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<p>Olvidaos por ahora de la tabla “Pruebas de <span class="math inline">\(\chi^2\)</span>” que aparece en el resultado, ya hablaremos de ella al hablar de contrastes de proporciones. Podéis impedir que aparezca desmarcando la casilla <span class="math inline">\(\chi^2\)</span> en la pestaña <em>Estadísticas</em>, que sale marcada por defecto.</p>
</section>
<section id="diagramas-de-barras-bidimensionales" class="level3" data-number="3.0.3">
<h3 data-number="3.0.3" class="anchored" data-anchor-id="diagramas-de-barras-bidimensionales"><span class="header-section-number">3.0.3</span> Diagramas de barras bidimensionales</h3>
<p>Una tabla de frecuencias bidimensional se suele representar mediante un diagrama de barras bidimensional, que puede ser:</p>
<ul>
<li><p><strong>De barras apiladas</strong>: Se escoge una variable (la llamaremos <strong>principal</strong>), se dibuja una barra para cada uno de sus niveles de altura la frecuencia total de dicho nivel, y cada una de estas barras se divide verticalmente en sectores que representan las frecuencias de los niveles de la otra variable dentro de ese nivel.</p>
<p>Por ejemplo, el diagrama de barras apiladas de frecuencias absolutas de las variables “Sexo” y “Demencia”, tomando la variable “Sexo” como principal:</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>De barras yuxtapuestas</strong>. Se escoge una variable <strong>principal</strong> y para cada uno de sus niveles se dibuja un diagrama de barras de las frecuencias de los niveles de la otra variable.</p>
<p>Así, el diagrama de barras yuxtapuestas de frecuencias absolutas de las variables “Sexo” y “Demencia”, tomando la variable “Sexo” como principal es:</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Otros dos ejemplos:</p>
<ul>
<li>El diagrama de barras apiladas de frecuencias absolutas de las variables “Sexo” y “Demencia”, tomando la variable “Demencia” como principal es:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>El diagrama de barras yuxtapuestas de frecuencias absolutas de las variables “Sexo” y “Demencia”, tomando la variable “Demencia” como principal:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los diagramas de barras tienen que mostrar la información de la manera más adecuada posible. Por ejemplo, si lo que nos interesa es la distribución de los tipos de demencia por sexo, la variable principal ha de ser el “Sexo”. Si nos interesan las frecuencias relativas globales, seguramente sea más conveniente dar un diagrama de barras tomando como niveles las combinaciones de niveles de ambas variables, como el siguiente diagrama de barras de frecuencias relativas globales de las variables “Sexo” y “Demencia”:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>El usar barras apiladas o yuxtapuestas en un diagrama de barras bidimensional ya va más a gusto de cada uno. Como un diagrama de barras yuxtapuestas usa tantas barras como el producto de los números de niveles de las dos variables, si estos dos números son grandes puede necesitar mucho espacio horizontal para ser comprensible. Por otro lado, en los diagramas de barras apiladas es más fácil comparar las frecuencias de los niveles de la variable principal, mientras que en los diagramas de barras yuxtapuestas es más fácil comparar la distribución de los niveles de la variable secundaria dentro de cada nivel de la variable principal.</p>
<p>Lo diagramas de barras bidimensionales se obtienen con las casillas adecuadas de la pestaña <em>Gráficos</em> en <strong>Frecuencias/Muestras independientes</strong>. Podéis elegir si queréis las barras apiladas (<em>Alineados</em>) o yuxtapuestas (<em>Al lado</em>), si el diagrama de barras ha de ser de frecuencias abolutas o relativas y en este último caso qué tipo de frecuencias relativas (del total, por filas o por columnas) y si la variable principal es la de las filas o las columnas. Por ejemplo, el diagrama de barras yuxtapuestas de frecuencias absolutas de las variables “Sexo” y “Demencia”, tomando la variable “Demencia” como principal, se obtiene de la manera siguiente:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-9.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</section>
<section id="ejercicio" class="level3" style="color: blue;" data-number="3.0.4">
<h3 style="color: blue;" data-number="3.0.4" class="anchored" data-anchor-id="ejercicio"><span class="header-section-number">3.0.4</span> Ejercicio</h3>
<p>En un estudio transversal en el que se analizó 75 hombres y 70 mujeres, 40 hombres y 20 mujeres presentaron una determinada enfermedad.</p>
<ol type="a">
<li><p>Representad estos datos en un diagrama de barras bidimensional de frecuencias relativas que muestre las proporciones de enfermos y sanos en cada sexo.</p></li>
<li><p>¿Qué vale la frecuencia relativa de los hombres entre los participantes que no presentaron la enfermedad?</p></li>
</ol>
</section>
<section id="diagramas-de-mosaico" class="level3" data-number="3.0.5">
<h3 data-number="3.0.5" class="anchored" data-anchor-id="diagramas-de-mosaico"><span class="header-section-number">3.0.5</span> Diagramas de mosaico</h3>
<p>Una tabla tridimensional se puede representar mediante un <strong>diagrama de mosaico</strong>. Estos gráficos se obtienen sustituyendo cada entrada de la tabla de frecuencias por una región rectangular de área proporcional a su valor. Por ejemplo, los “Sí” y “No” de la fila superior corresponden a la variable “Cancer”:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="descripción-de-datos-ordinales" class="level3" data-number="3.0.6">
<h3 data-number="3.0.6" class="anchored" data-anchor-id="descripción-de-datos-ordinales"><span class="header-section-number">3.0.6</span> Descripción de datos ordinales</h3>
<p>Los <strong>datos ordinales</strong> son parecidos a los cualitativos, en el sentido de que son cualidades de objetos o individuos. Su diferencia con los datos cualitativos está en que las características que expresan los datos ordinales tienen un orden natural que permite <strong>acumular</strong> observaciones, es decir, contar cuántas hay por debajo de cada nivel. Un caso frecuente son las escalas tipo <em>Likert</em>, que se usan para expresar el nivel de acuerdo o desacuerdo con una afirmación mediante respuestas cerradas.</p>
<strong>Ejemplo:</strong>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; padding: 10px; margin: 10px 0;">
<p>En una encuesta sobre la actitud de personal sanitario frente al dolor (M. E. Zanolin <em>et al</em>, “A questionnaire to evaluate the knowledge and attitudes of health care providers on pain”, <em>Journal of pain and symptom management</em> 33 (2007), pp.&nbsp;727-736), se pidió el grado de conformidad con afirmaciones como:</p>
<ul>
<li><p>Como los narcóticos pueden causar depresión respiratoria, no se han de usar en pacientes pediátricos.</p></li>
<li><p>Es útil dar de entrada un placebo al paciente que se queja de dolor para saber si realmente siente dolor.</p></li>
</ul>
<p>según la escala Likert siguiente:</p>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Nivel</th>
<th style="text-align: left;">Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Muy en desacuerdo</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">En desacuerdo</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Neutral</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">De acuerdo</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Muy de acuerdo</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Las respuestas a este tipo de cuestionarios son números, pero no son datos cuantitativos, sino ordinales: meras abreviaturas de los diferentes grados de conformidad.</p>
<p>Para más información sobre escalas Likert, podéis consultar <a href="http://es.wikipedia.org/wiki/Escalas_Likert">la correspondiente entrada de la Wikipedia</a>.</p>
<p>Cuando trabajamos con datos ordinales, el orden de los niveles de los datos permite calcular no sólo las frecuencias absolutas y relativas que veíamos en la lección anterior, y que para variables ordinales se definen del mismo modo, sino también frecuencias <strong>acumuladas</strong>. Es decir, no sólo podemos contar cuántas veces hemos observado un cierto nivel, sino también cuántas veces hemos observado un nivel menor o igual que él. Por lo tanto, su descripción estadística es la misma que para datos cualitativos, más:</p>
<ul>
<li><p><strong>Frecuencias absolutas acumuladas</strong>: El número de veces que aparece en la muestra un nivel menor o igual que el considerado.</p></li>
<li><p><strong>Frecuencias relativas acumuladas</strong>: La fracción del total de la muestra que representan los niveles menores o iguales que el considerado.</p></li>
</ul>
<p>De nuevo, estas frecuencias acumuladas se pueden recoger en una <strong>tabla</strong> y representar en forma de <strong>diagrama de barras</strong> (con los niveles ordenados en orden creciente).</p>
<strong>Ejemplo:</strong>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; padding: 10px; margin: 10px 0;">
<p>Tenemos una muestra de 20 estudiantes de quienes sabemos la calificación que han sacado en un examen. Clasificamos estas calificaciones en Suspenso (<em>S</em>), Aprobado (<em>A</em>), Notable (<em>N</em>) y Sobresaliente (<em>E</em>) y consideramos su orden natural <em>S</em> &lt; <em>A</em> &lt; <em>N</em> &lt; <em>E</em>. Las calificaciones que han obtenido son las siguientes:</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>N, A, A, S, S, A, N, E, A, A, S, S, S, A, E, N, N, E, S, A</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>En esta lista hay 6 <em>S</em>, 7 <em>A</em>, 4 <em>N</em> y 3 <em>E</em>: éstas serían las frecuencias absolutas de las calificaciones en esta muestra de estudiantes. Por lo que se refiere a sus <strong>frecuencias absolutas acumuladas</strong>:</p>
<ul>
<li>Hay 6 estudiantes que han obtenido <em>S</em> o menos: la frecuencia acumulada de <em>S</em> es 6.</li>
<li>Hay 13 estudiantes que han obtenido <em>A</em> o menos (6 <em>S</em> y 7 <em>A</em>): la frecuencia acumulada de <em>A</em> es 13.</li>
<li>Hay 17 estudiantes que han obtenido <em>N</em> o menos (6 <em>S</em>, 7 <em>A</em> y 4 <em>N</em>): la frecuencia acumulada de <em>N</em> es 17.</li>
<li>Hay 20 estudiantes que han obtenido <em>E</em> o menos (todos): la frecuencia acumulada de <em>E</em> es 20.</li>
</ul>
<p>La <strong>frecuencia relativa acumulada</strong> de cada calificación es la fracción del total de estudiantes que representa su frecuencia absoluta acumulada. Por ejemplo, la frecuencia relativa acumulada de notables es la proporción de estudiantes que han sacado un notable o menos, y, por lo tanto, es igual a la frecuencia absoluta acumulada de <em>N</em> dividida por el número total de estudiantes: 17/20=0.85. También se puede obtener “acumulando” las frecuencias relativas de las calificaciones menores o iguales que <em>N</em>: como hay un 30% de <em>S</em> (6 de 20), un 35% de <em>A</em> (7 de 20) y un 20% de <em>N</em> (4 de 20), la frecuencia relativa acumulada de <em>N</em> es 0.3+0.35+0.2=0.85, es decir, un 85%.</p>
<p>Así pues, las frecuencias relativas acumuladas de las calificaciones en esta muestra son:</p>
<ul>
<li>Frecuencia relativa acumulada de <em>S</em>: 6/20=0.3.</li>
<li>Frecuencia relativa acumulada de <em>A</em>: 13/20=0.65.</li>
<li>Frecuencia relativa acumulada de <em>N</em>: 17/20=0.85.</li>
<li>Frecuencia relativa acumulada de <em>E</em>: 20/20=1.</li>
</ul>
<p>Resumimos todos estos valores en la tabla siguiente:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Frecuencia absoluta</th>
<th style="text-align: right;">Frecuencia relativa</th>
<th style="text-align: left;">Porcentaje</th>
<th style="text-align: right;">Frecuencia absoluta acumulada</th>
<th style="text-align: right;">Frecuencia relativa acumulada</th>
<th style="text-align: left;">Porcentaje acumulado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Suspenso</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: left;">30%</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: left;">30%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aprobado</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: left;">35%</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: left;">65%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Notable</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: left;">20%</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: left;">85%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sobresaliente</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: left;">15%</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">100%</td>
</tr>
</tbody>
</table>
</div>
</div>
<strong>Ejemplo:</strong>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; padding: 10px; margin: 10px 0;">
<p>Todos los ancianos recogidos en la tabla de datos del Ejemplo presentado con anterioridad fueron diagnosticados con COVID-19 entre marzo y mayo de 2020. Vamos a ampliar dicha tabla de datos con información sobre la gravedad de su enfermedad, clasificada en cuatro niveles: Asintomática, Leve, Hospitalización (si requirió hospitalización pero no en UCI) y UCI. Consideraremos esta variable como ordinal, con sus niveles ordenados en orden creciente de gravedad.</p>
</div>
<p>La tabla de datos ampliada es la siguiente:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-condensed caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla de datos de pacientes de residencias geriátricas</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">Sexo</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">Demencia Senil</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">Cáncer de mama</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">COVID-19</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">Sí</td>
<td style="text-align: left;">UCI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Asintomática</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">Sí</td>
<td style="text-align: left;">Hospitalización</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">UCI</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Otros</td>
<td style="text-align: left;">Sí</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Hospitalización</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Asintomática</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Sí</td>
<td style="text-align: left;">Asintomática</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Hospitalización</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Hospitalización</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Leve</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Entonces:</p>
<ul>
<li>La tabla de frecuencias absolutas de la variable <em>COVID-19</em> es:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">COVID-19</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Frecs.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asintomática</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leve</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospitalización</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">UCI</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>Su tabla de frecuencias relativas:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">COVID-19</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Frecs.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asintomática</td>
<td style="text-align: right;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leve</td>
<td style="text-align: right;">0.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospitalización</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">UCI</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>Su tabla de frecuencias absolutas acumuladas:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">COVID-19</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Frecs. Acum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asintomática</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leve</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospitalización</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">UCI</td>
<td style="text-align: right;">20</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>Su tabla de frecuencias relativas acumuladas:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">COVID-19</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Frecs. Acum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asintomática</td>
<td style="text-align: right;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leve</td>
<td style="text-align: right;">0.70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospitalización</td>
<td style="text-align: right;">0.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">UCI</td>
<td style="text-align: right;">1.00</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>Su diagrama de barras de frecuencias absolutas acumuladas:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Su diagrama de barras de frecuencias relativas acumuladas:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>La tabla bidimensional de frecuencias absolutas de las variables Demencia Senil y COVID-19:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Asintomática</th>
<th style="text-align: right;">Leve</th>
<th style="text-align: right;">Hospitalización</th>
<th style="text-align: right;">UCI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Otros</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Su tabla de frecuencias relativas acumuladas dentro de cada nivel de demencia senil:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Asintomática</th>
<th style="text-align: right;">Leve</th>
<th style="text-align: right;">Hospitalización</th>
<th style="text-align: right;">UCI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alzheimer</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.625</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Otros</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.750</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.750</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>El diagrama de barras yuxtapuestas de esta última tabla:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t3_losDatosTipos_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como vimos antes, Jamovi da las frecuencias acumuladas (si hemos especificado correctamente el orden de los niveles) al calcular tablas de contigencia en <strong>Exploración/Descriptivas</strong>. En las tablas multidimensionales la acumulación se lleva a cabo en el total, lo que no siempre es conveniente. Para calcular bien tablas bidimensionales acumulando frecuencias por filas o columnas hay que usar R en la ventana de edición <strong>R</strong>. Por ejemplo, para obtener la tabla de frecuencias relativas acumuladas que hemos dado hace un momento de niveles de gravedad de la COVID dentro de cada nivel de demencia senil podemos usar:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/Jamovi-ed-10.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<p>Fijaos en la lógica de la sintaxis de esta instrucción. De dentro a fuera:</p>
<ul>
<li><p><code>table(data$Demencia, data$COVID)</code> calcula la tabla de frecuencias absolutas de las variables Demencia y COVID, con filas la Demencia.</p></li>
<li><p><code>prop.table(..., margin=1)</code> calcula la tabla de frecuencias relativas (de proporciones) por filas (<code>margin=1</code>) de la tabla de frecuencias absolutas a la que se aplica en los puntos suspensivos.</p></li>
<li><p><code>apply(..., MARGIN=1, FUN=cumsum)</code> aplica la función <code>cumsum</code>, que calcula las sumas acumuladas, por filas (<code>MARGIN=1</code>) a la tabla entrada en los puntos suspensivos.</p></li>
</ul>
<p>Esta última función transpone nuestra tabla (siempre da el resultado de manera que la dimensión en la que se acumulan las frecuencias sea la de las columnas); si quisiérais mantener los tipos de demencia en la filas, se aplicaría <code>t(...)</code> al resultado del <code>apply</code>.</p>
<p><strong>Ejercicio</strong></p>
<p>Calculad la tabla bidimensional de frecuencias relativas acumuladas de los niveles de gravedad de la COVID-19 en cada sexo, y representad esta tabla por medio de un diagrama de barras yuxtapuestas adecuado.</p>
</section>
<section id="descripción-de-datos-cuantitativos" class="level3" data-number="3.0.7">
<h3 data-number="3.0.7" class="anchored" data-anchor-id="descripción-de-datos-cuantitativos"><span class="header-section-number">3.0.7</span> Descripción de datos cuantitativos</h3>
<p>Los <strong>datos cuantitativos</strong> son los que expresan cantidades que se representan mediante números, tales como los resultados de contar objetos o individuos o de medir pesos, distancias, tiempos o concentraciones.</p>
<p>Como los números reales están ordenados de manera natural, para estudiar una muestra de datos cuantitativos (una <strong>variable cuantitativa</strong>) podemos usar las frecuencias y las frecuencias acumuladas de sus diferentes valores, como en las variables ordinales. Esto realmente solo es útil cuando en la muestra tenemos pocos valores diferentes.</p>
<p>Como los datos cuantitativos son números reales y tienen el significado de números reales, podemos operar con ellos. Esto nos aporta una multitud de <strong>estadísticos</strong>, expresiones matemáticas que, aplicadas a un vector de datos cuantitativos, producen valores que expresan diferentes características del mismo.</p>
<p>Supongamos de ahora en adelante que tenemos una muestra formada por <span class="math inline">\(n\)</span> números, que denotaremos <span class="math inline">\(x_1,\ldots,x_n\)</span>.</p>
<p>En primer lugar tenemos los <strong>estadísticos de tendencia central</strong>, que dan un valor representativo del conjunto de datos de la variable; los más importantes son:</p>
<ul>
<li><p>La <strong>moda</strong>, que es el valor, o los valores, de máxima frecuencia (absoluta o relativa, tanto da). Normalmente, solo se usa para variables discretas.</p></li>
<li><p>La <strong>media aritmética</strong>: <span class="math display">\[
\overline{x}=\frac{x_1+\cdots+x_n}{n}
\]</span></p>
<p>En este curso, cuando hablemos de la <em>media</em> de unos datos nos referiremos siempre a su media aritmética. Hay otros tipos de media, como por ejemplo la media geométrica o la armónica, que no estudiaremos.</p></li>
<li><p>La <strong>mediana</strong> <span class="math inline">\(Q_{0.5}\)</span>, que representa el valor central en la lista ordenada de observaciones. Se define de la manera siguiente. Si denotamos por <span class="math display">\[
x_{(1)}\leqslant x_{(2)}\leqslant \cdots \leqslant x_{(n)}
\]</span> los datos de la variable cuantitativa ordenados de menor a mayor:</p>
<ul>
<li><p>Si <span class="math inline">\(n\)</span> es impar, su mediana es el dato central: <span class="math inline">\(x_{(n+1)/2}\)</span>.</p>
<p>Por ejemplo, si una muestra está formada por 7 números, su mediana es el cuarto tras ordenarlos de menor a mayor.</p></li>
<li><p>Si <span class="math inline">\(n\)</span> es par, su mediana es la media de los dos datos centrales: <span class="math display">\[
\frac{x_{(n/2)}+x_{(n/2+1)}}{2}.
\]</span></p>
<p>Por ejemplo, si una muestra está formada por 8 números, su mediana es la media del cuarto y el quinto tras ordenarlos de menor a mayor.</p></li>
</ul></li>
</ul>
<p>Tomemos la variable “Hijos” de la Tabla @ref(tab:tablager4), formada por los números</p>
<p style="text-align:center">
4, 1, 8, 0, 3, 4, 2, 1, 1, 2, 6, 0, 0, 1, 4, 2, 0, 3, 6, 3
</p>
<ul>
<li><p>En su tabla de frecuencias vemos que la <em>moda</em> son los valores 0 y 1, que empatan en la frecuencia máxima.</p></li>
<li><p>Su <em>media</em> es <span class="math display">\[
\frac{4+1+8+0+3+\cdots+0+3+6+3}{20}=2.55
\]</span></p></li>
<li><p>Para calcular su <em>mediana</em>, lo primero que hacemos es ordenar de menor a mayor las observaciones, y marcamos su posición dentro del conjunto ordenado:</p></li>
</ul>
<p>Como tenemos 20 datos, la mediana será la media aritmética de sus dos valores centrales, los de las posiciones 10 y 11: <span class="math inline">\(Q_{0.5}=(2+2)/2=2\)</span>.</p>
<p>¿Qué les pasa a estos estadísticos si eliminamos el paciente con 8 hijos de la muestra? Los datos son ahora</p>
<p style="text-align:center">
4, 1, 0, 3, 4, 2, 1, 1, 2, 6, 0, 0, 1, 4, 2, 0, 3, 6, 3
</p>
<ul>
<li><p>La <em>moda</em> siguen siendo los valores 0 y 1, ya que no hemos modificado sus frecuencias y hemos eliminado observaciones</p></li>
<li><p>Su <em>media</em> ahora es <span class="math display">\[
\frac{4+1+0+3+\cdots+0+3+6+3}{19}=2.263
\]</span></p></li>
<li><p>Como ahora tenemos 19 observaciones, su mediana será la observación central, es decir, la décima tras ordenarlas de menor a mayor:</p></li>
</ul>
<p>Por lo tanto, <span class="math inline">\(Q_{0.5}=2\)</span>.</p>
<p>¿Y qué les pasaría a estos estadísticos si, en la muestra original, hubiéramos cometido un error y al último paciente le hubiéramos anotado 300 hijos en lugar de 3? Los datos así serían:</p>
<p style="text-align:center">
4, 1, 8, 0, 3, 4, 2, 1, 1, 2, 6, 0, 0, 1, 4, 2, 0, 3, 6, 300
</p>
<ul>
<li><p>La <em>moda</em> no cambia</p></li>
<li><p>La <em>media</em> ahora sería <span class="math display">\[
\frac{4+1+8+0+3+\cdots+0+3+6+300}{20}=17.4
\]</span></p></li>
<li><p>Como volvemos a tener 20 números, la <em>mediana</em> sería otra vez la media de las observaciones décima y undécima tras ordenarlas de menor a mayor:</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Posición</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valor</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">300</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>De nuevo, <span class="math inline">\(Q_{0.5}=(2+2)/2=2\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es importante observar que:</p>
<ul>
<li><p>La moda es el valor más repetido, pero puede ser poco representativa y puede carecer completamente de interés si, por ejemplo, todos los valores de la muestra tienen frecuencias muy parecidas.</p></li>
<li><p>La media es poco robusta, en el sentido de que los valores extremos pueden afectarla mucho</p></li>
<li><p>La mediana es muy robusta, en el sentido de que los valores extremos la afectan poco</p></li>
</ul>
</div>
</div>
<p>Por este motivo, por ejemplo, a la hora de resumir los salarios españoles, se publican los tres valores:</p>
<figure style="text-align: center" ;="" class="figure">
  <img src="Figuras/salarios.png" width="80%" class="figure-img">
  <figcaption>Gráfico publicado por el INE  (https://www.ine.es/prensa/eces_2018_a.pdf).</figcaption>
  </figure>
<p>Es interesante copiar un trozo de la nota de prensa de la que hemos extraído el gráfico, donde se comenta la relación entre la moda, la media y la mediana:</p>
<blockquote class="blockquote">
<p>“El salario bruto medio anual en España fue de 24.009,12 euros por trabajador en el año 2018, un 1,5% mayor al año anterior. La diferencia entre este salario medio y el salario más frecuente o modal (de 18.468,93 euros) fue de más de 5.500 euros. Esto significa que había pocos trabajadores con salarios muy altos pero que influyeron notablemente en el salario medio.</p>
</blockquote>
<blockquote class="blockquote">
<p>“Por otra parte, el salario mediano (que divide al número de trabajadores en dos partes iguales, los que tienen un salario superior y los que tienen un salario inferior) presentó un valor de 20.078,44 euros en 2018.”</p>
</blockquote>
<p><strong>Medidas de posición</strong></p>
<p>Las <strong>medidas de posición</strong> dividen la variable en unas determinadas proporciones; estos valores reciben el nombre de <strong>cuantiles</strong>. En este sentido, la mediana es también una medida de posición, puesto que divide la variable en dos mitades.</p>
<p>Dada una proporción <span class="math inline">\(0&lt;p&lt;1\)</span>, el <strong>cuantil de orden <span class="math inline">\(p\)</span></strong>, o <strong><span class="math inline">\(p\)</span>-cuantil</strong>, de una variable cuantitativa, que denotaremos por <span class="math inline">\(Q_p\)</span>, es el valor más pequeño del conjunto de datos cuya frecuencia relativa acumulada es mayor o igual que <span class="math inline">\(p\)</span>; o sea, el valor más pequeño de la muestra que es mayor o igual que el <span class="math inline">\(100p\%\)</span> de los valores de la muestra. Dicho de una tercera manera, si tenemos un conjunto de números <span class="math inline">\(x_1, \ldots, x_n\)</span> y los ordenamos de menor a mayor, <span class="math display">\[
x_{(1)}\leqslant x_{(2)}\leqslant \cdots \leqslant x_{(n)},
\]</span> entonces <span class="math inline">\(Q_p\)</span> es el primer valor <span class="math inline">\(x_{(i)}\)</span> de esta lista ordenada que deja a su izquierda (incluyéndolo a él) como mínimo la fracción <span class="math inline">\(p\)</span> de los datos, es decir, <span class="math inline">\(p\cdot n\)</span> datos.</p>
<p>La excepción a esta regla es el cuantil <span class="math inline">\(Q_{0.5}\)</span>, que es la mediana y se calcula como hemos explicado antes.</p>
<strong>Ejemplo:</strong>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; padding: 10px; margin: 10px 0;">
<p>Considera la variable “Hijos” que registra el número de hijos vivos en el momento de ingreso de unos pacientes en sus residencias geriátricas. Sus 20 valores, ordenados de menor a mayor son:</p>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">Posicion</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valor</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Entonces:</p>
<ul>
<li><p>El 0.2-cuantil, <span class="math inline">\(Q_{0.2}\)</span>, es el primer elemento en esta lista ordenada que es mayor o igual que el 20% de los datos. Como el 20% de 20 es 4, <span class="math inline">\(Q_{0.2}\)</span> es el cuarto elemento de la lista ordenada: 0.</p></li>
<li><p>El 0.75-cuantil, <span class="math inline">\(Q_{0.75}\)</span>, es el primer elemento en esta lista ordenada que es mayor o igual que el 75% de los datos. Como el 75% de 20 es 15, <span class="math inline">\(Q_{0.75}\)</span> es el decimoquinto elemento de la lista ordenada: 4.</p></li>
<li><p>El cuantil de orden 1/3, <span class="math inline">\(Q_{1/3}\)</span>, es el primer elemento en esta lista ordenada que es mayor o igual que un tercio de los datos. Como un tercio de 20 es 6.66 y pico, <span class="math inline">\(Q_{1/3}\)</span> es el <em>séptimo</em> elemento de la lista ordenada: 1. Fijaos en que 6/20=0.3, y por lo tanto el sexto elemento de la lista solo es mayor o igual que el 30% de la muestra, no un tercio. Necesitamos el séptimo elemento para llegar al tercio, aunque entonces nos pasemos.</p></li>
</ul>
<p>Los cuantiles se calculan a partir de los valores ordenados de la muestra, teniendo en cuenta los valores repetidos. Es decir, si se han observado un 1, un 2, un 3, un 4 y cinco 5, la mediana no es el valor central de 1, 2, 3, 4, 5, sino el de 1, 2, 3, 4, 5, 5, 5, 5, 5, que es 5.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>En realidad, la definición que hemos dado de cuantil es “orientativa”: no hay una regla única para calcular cuantiles de una muestra (<em>salvo la mediana</em>), y se han propuesto varios métodos que pueden dar resultados diferentes; podéis consultar nueve de estos métodos en la <a href="https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample">entrada sobre cuantiles de la Wikipedia en inglés</a>. La razón de esta diversidad es que a veces el objetivo final del cálculo de un cuantil no es solo descriptivo (dar el menor valor mayor o igual que una fracción <span class="math inline">\(p\)</span> <em>de la muestra</em>) sino que es inferencial (estimar el menor valor que es mayor o igual que una fracción <span class="math inline">\(p\)</span> <em>del total de la población</em>) y esta inferencia se puede hacer de muchas maneras, según las propiedades que tenga (o que supongamos que tenga) la población.</p>
<p>¿Qué os recomendamos? No os compliquéis la vida:</p>
<ul>
<li>Si calculáis cuantiles a mano, usad la definición que hemos dado, que es la más sencilla de todas</li>
<li>Si los calculáis con algún paquete estadístico, usad su método por defecto (que seguramente no sea el que hemos explicado)</li>
</ul>
</div>
</div>
<p>Algunos cuantiles con nombre propio:</p>
<ul>
<li><p>La <strong>mediana</strong> es el cuantil <span class="math inline">\(Q_{0.5}\)</span>.</p></li>
<li><p>Los <strong>cuartiles</strong> son los cuantiles <span class="math inline">\(Q_{0.25}\)</span>, <span class="math inline">\(Q_{0.5}\)</span> y <span class="math inline">\(Q_{0.75}\)</span>, y reciben, respectivamente, los nombres de <strong>primer cuartil</strong>, <strong>segundo cuartil</strong> (o mediana) y <strong>tercer cuartil</strong>. <span class="math inline">\(Q_{0.25}\)</span> será, pues, el menor valor que es mayor o igual que una cuarta parte de los datos, y <span class="math inline">\(Q_{0.75}\)</span>, el menor valor que es mayor o igual que tres cuartas partes de los datos.</p></li>
<li><p>Los <strong>deciles</strong> son los cuantiles <span class="math inline">\(Q_{p}\)</span> con <span class="math inline">\(p\)</span> un múltiplo entero de 0.1: el <strong>primer decil</strong> es <span class="math inline">\(Q_{0.1}\)</span>, el <strong>segundo decil</strong> es <span class="math inline">\(Q_{0.2}\)</span>, y así sucesivamente.</p></li>
<li><p>Los <strong>percentiles</strong> son los cuantiles <span class="math inline">\(Q_{p}\)</span> con <span class="math inline">\(p\)</span> un múltiplo entero de 0.01: <span class="math inline">\(Q_{0.01}\)</span> es el <strong>primer percentil</strong>, <span class="math inline">\(Q_{0.02}\)</span> es el <strong>segundo percentil</strong>, etc.</p></li>
</ul>
<p>Se llama <strong>intervalo intercuartílico</strong>, <span class="math inline">\(\mathit{IQI}\)</span>, al intervalo cerrado <span class="math inline">\([Q_{0.25},Q_{0.75}]\)</span>. Fijaos que como un 75% de los datos de la muestra son menores o iguales que <span class="math inline">\(Q_{0.75}\)</span> y, de estos, un 25% son menores o iguales que <span class="math inline">\(Q_{0.25}\)</span>, dentro del <span class="math inline">\(\mathit{IQI}\)</span> caerán más o menos el 50% de los datos de la muestra, a no ser que haya muchas repeticiones en los extremos del intervalo.</p>
<strong>Ejemplo:</strong>
<div style="border-left: 4px solid #f0ad4e; background-color: #fcf8e3; padding: 10px; margin: 10px 0;">
<p>Seguimos con la variable “Hijos”. Su primer cuartil será su quinto dato tras ordenarlos de menor a mayor; como hay cuatro ceros y cuatro unos, será 1. Su tercer cuartil ya lo hemos calculado antes, es 4. Por lo tanto su intervalo intercuartílico es [1,4]. Este intervalo contiene 14 elementos de la muestra, bastante más de la mitad, porque la muestra contiene muchas repeticiones del 1 y el 4.</p>
</div>
<p>Las medidas de posición también se pueden, y se suelen, usar en la descripción de datos ordinales. En este caso, la mediana se define como el primer valor de la muestra mayor o igual que (al menos) la mitad de la muestra. El resto de cuantiles se definen como los hemos definido aquí.</p>
<p><strong>Ejercicio</strong> Aquí tenéis una muestra de 14 niveles de glucosa medidos en niños en ayunas:</p>
<p style="text-align:center">
56, 60, 62, 63, 63, 65, 65, 66, 66, 66, 66, 68, 70, 72
</p>
<p>Calculad su:</p>
<ul>
<li>Moda</li>
<li>Media</li>
<li>Mediana</li>
<li>Primer y tercer cuartiles</li>
<li>Porcentaje de elementos de la muestra que caen dentro del intervalo intercuartílico</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/Cruzalirio\.github\.io\/Farmacia");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./t2_intro.html" class="pagination-link" aria-label="Representación gráfica y análisis de Datos">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Representación gráfica y análisis de Datos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./referencias.html" class="pagination-link" aria-label="Referencias">
        <span class="nav-page-text">Referencias</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Matématicas y Estadística para Farmacia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Cruzalirio/Farmacia/edit/main/t3_losDatosTipos.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/Cruzalirio/Farmacia/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Este libro se ha creado con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>